Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/shield-gh.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &RSU1
    Name: RSU1MSP
    ID: RSU1MSP
    MSPDir: crypto-config/peerOrganizations/rsu1.shield-gh.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RSU1MSP.admin', 'RSU1MSP.peer', 'RSU1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('RSU1MSP.admin', 'RSU1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RSU1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('RSU1MSP.peer')"

  - &RSU2
    Name: RSU2MSP
    ID: RSU2MSP
    MSPDir: crypto-config/peerOrganizations/rsu2.shield-gh.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RSU2MSP.admin', 'RSU2MSP.peer', 'RSU2MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('RSU2MSP.admin', 'RSU2MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RSU2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('RSU2MSP.peer')"

  - &RSU3
    Name: RSU3MSP
    ID: RSU3MSP
    MSPDir: crypto-config/peerOrganizations/rsu3.shield-gh.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RSU3MSP.admin', 'RSU3MSP.peer', 'RSU3MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('RSU3MSP.admin', 'RSU3MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RSU3MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('RSU3MSP.peer')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.shield-gh.com:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.shield-gh.com
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/shield-gh.com/orderers/orderer.shield-gh.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/shield-gh.com/orderers/orderer.shield-gh.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ShieldGHGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      ShieldGHConsortium:
        Organizations:
          - *RSU1
          - *RSU2
          - *RSU3

  ShieldGHChannel:
    Consortium: ShieldGHConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *RSU1
        - *RSU2
        - *RSU3
      Capabilities:
        <<: *ApplicationCapabilities
